steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'my-service',
      '--source', '.',
      '--region', 'us-east4',
      '--allow-unauthenticated'
    ]
serviceAccount: camp-477922@appspot.gserviceaccount.com
options:
  logging: CLOUD_LOGGING_ONLY
